# @see https://starship.rs/

[directory]
truncation_length = 255
truncate_to_repo = false

[hostname]
ssh_only = false
style = "bright-green bold"
format = "@[$hostname]($style): "
disabled = false

[username]
style_user = "bright-blue bold"
style_root = "red bold"
format = "[$user]($style)"
show_always = true
disabled = false

[git_branch]
style = "#ff9000 bold"

# @see https://starship.rs/config/#kubernetes
[kubernetes]
disabled = false
symbol = "⎈"
style = "dimmed green"
format = 'on [$symbol $context( \($namespace\)) ]($style)'
