name: Actionlint

on:
  workflow_dispatch:
  push:

jobs:
  actionlint:
    runs-on: ubuntu-22.04
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download actionlint
        id: get_actionlint
        shell: bash
        run: bash <(curl https://raw.githubusercontent.com/rhysd/actionlint/main/scripts/download-actionlint.bash)

      - name: Check workflow files
        shell: bash
        run: ${{ steps.get_actionlint.outputs.executable }} -color -shellcheck=
