name: Detect Secrets

on:
  workflow_dispatch:
  push:

jobs:
  detect-secrets:
    runs-on: ubuntu-22.04
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download detect-secrets
        shell: bash
        env:
          VERSION: '1.4.0'
        run: |
          pip install detect-secrets==$VERSION

      - name: Run detect-secrets
        shell: bash
        env:
          BASELINE: '.secrets.baseline.json'
        run: |
          git ls-files -z | xargs -0 detect-secrets-hook --verbose --baseline $BASELINE
